# Generated by Django 6.0 on 2026-01-20 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('67875004-8178-4492-9065-b993a1cde39c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
