# Generated by Django 6.0 on 2026-01-24 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b237b2c0-2a85-480e-a744-e28284c56322'), editable=False, primary_key=True, serialize=False),
        ),
    ]
