FROM python:3.14-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY . .

EXPOSE 8000

CMD uv run python manage.py migrate && \
    uv run python manage.py seed_data && \
    uv run python manage.py runserver 0.0.0.0:8000
