# Generated by Django 6.0 on 2026-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='currency',
        ),
    ]
