# Generated by Django 6.0 on 2026-01-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
