# Generated by Django 6.0 on 2025-12-26 01:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('court_type', models.CharField()),
                ('type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=16)),
                ('surface', models.CharField(choices=[('clay', 'Clay'), ('grass', 'Grass'), ('hard', 'Hard')], max_length=16)),
                ('max_players', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourtPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'Euro')], default='PLN', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='courts.court')),
            ],
        ),
    ]
