# Generated by Django 6.0 on 2026-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtprice',
            name='currency',
        ),
        migrations.AddConstraint(
            model_name='courtprice',
            constraint=models.UniqueConstraint(fields=('court',), name='uniq_court_price'),
        ),
    ]
