# Generated by Django 6.0 on 2025-12-26 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a13c71fb-f3f2-4d12-bb61-ced1c709d228'), editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('transfer', 'Bank Transfer'), ('in_person', 'Payment in person')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
