# Generated by Django 6.0 on 2025-12-27 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('411e61ce-610b-4d6b-933d-ec4e6b25c028'), editable=False, primary_key=True, serialize=False),
        ),
    ]
