# Generated by Django 6.0 on 2025-12-27 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e31e4219-26c4-4b9a-9b2e-5a79ebd6d436'), editable=False, primary_key=True, serialize=False),
        ),
    ]
